# Generated by Django 5.1.4 on 2025-01-20 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="partner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="unique_code",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
