# Generated by Django 5.1.4 on 2025-01-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_category_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="main.category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="Текст вопроса"),
        ),
    ]
