# Generated by Django 5.1.4 on 2025-01-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_answer_user_answer_is_correct_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useranswer",
            old_name="choosen_answer",
            new_name="chosen_answer",
        ),
    ]
